CREATE USER STAGE_SPARK IDENTIFIED BY STAGE_SPARK;

GRANT CONNECT,DBA TO STAGE_SPARK;

CREATE TABLE STAGE_SPARK.GRP02_PRS 
(
    ID_PER NUMBER(6,0), 
    MATRICOLA NUMBER(5,0), 
    CF VARCHAR2(100 BYTE), 
    DATA_PRES DATE, 
    OREPRES NUMBER(4,2), 
    ORESTRAOR NUMBER(4,2), 
    OREPERMES NUMBER(4,2)
) 
PARTITION BY RANGE (ID_PER)
(
    PARTITION P_202501 VALUES LESS THAN (202502)
);

CREATE TABLE STAGE_SPARK.GRP02_PRS_SCARTI 
(
    ID_PER VARCHAR(100), 
    MATRICOLA VARCHAR(100), 
    CF VARCHAR(100), 
    DATA_PRES VARCHAR(100), 
    OREPRES VARCHAR(100), 
    ORESTRAOR VARCHAR(100), 
    OREPERMES VARCHAR(100)
) 
PARTITION BY RANGE (ID_PER)
(
    PARTITION P_202501 VALUES LESS THAN (202502)
);

CREATE TABLE STAGE_SPARK.GRP02_RUO
(
    ID_PER NUMBER(6,0),
    COD_RUOLO VARCHAR2(10 BYTE),
    DESC_RUOLO VARCHAR2(100 BYTE)
)
PARTITION BY RANGE (ID_PER)
(
    PARTITION P_202501 VALUES LESS THAN (202502)
);

CREATE TABLE STAGE_SPARK.GRP02_UNT
(
    ID_PER NUMBER(6,0),
    COD_UNT NUMBER(5,0),
    DESC_UNT VARCHAR2(100 BYTE)
)
PARTITION BY RANGE (ID_PER)
(
    PARTITION P_202501 VALUES LESS THAN (202502)
);

CREATE TABLE STAGE_SPARK.GRP02_ANA
(
    ID_PER NUMBER(6,0),
    COD_DIP NUMBER(5,0),
    COD_UNT NUMBER(5,0),
    COD_RUOLO VARCHAR2(10 BYTE),
    COGNOME VARCHAR2(50 BYTE),
    NOME VARCHAR2(50 BYTE),
    DT_INI_UNT DATE,
    TIPO_CTR VARCHAR2(50 BYTE),
    COD_CTR VARCHAR2(10 BYTE),
    COD_LIV VARCHAR2(10 BYTE),
    DT_INI_LIV DATE,
    DT_INI_MNS DATE,
    MATRICOLA VARCHAR2(10 BYTE),
    CF VARCHAR2(16 BYTE),
    SESSO VARCHAR2(10 BYTE),
    DT_NASCITA DATE,
    TIPO_RAPP VARCHAR2(10 BYTE),
    DT_INI_TIPO_CTR DATE,
    DT_FINE_TIPO_CTR DATE,
    DT_INI_RAPP DATE,
    DT_FINE_RAPP DATE,
    AMBITO VARCHAR2(10 BYTE),
    TIPO_ASS VARCHAR2(10 BYTE),
    DT_PROROGA_TERMINE DATE,
    DT_CTR_SOST_MAT DATE,
    QTA_PART_TIME VARCHAR2(10 BYTE),
    TITOLARE1 VARCHAR2(50 BYTE),
    TITOLARE2 VARCHAR2(50 BYTE),
    MOTIVO_PROMOZIONE VARCHAR2(50 BYTE),
    FASCICOLO_AGGIORNATO VARCHAR2(50 BYTE),
    TITOLO_STUDIO VARCHAR2(10 BYTE),
    DESC_CTR VARCHAR2(50 BYTE),
    DESC_LIV VARCHAR2(50 BYTE)
)
PARTITION BY RANGE (ID_PER)
(
    PARTITION P_202501 VALUES LESS THAN (202502)
);

CREATE TABLE STAGE_SPARK.GRP02_RUO_SCARTI
(
    ID_PER VARCHAR(100),
    COD_RUOLO VARCHAR(100),
    DESC_RUOLO VARCHAR(100)
)
PARTITION BY RANGE (ID_PER)
(
    PARTITION P_202501 VALUES LESS THAN (202502)
);

CREATE TABLE STAGE_SPARK.GRP02_ANA_SCARTI
(
    ID_PER VARCHAR(100),
    COD_DIP VARCHAR(100),
    COD_UNT VARCHAR(100),
    COD_RUOLO VARCHAR(100),
    COGNOME VARCHAR(100),
    NOME VARCHAR(100),
    DT_INI_UNT VARCHAR(100),
    TIPO_CTR VARCHAR(100),
    COD_CTR VARCHAR(100),
    COD_LIV VARCHAR(100),
    DT_INI_LIV VARCHAR(100),
    DT_INI_MNS VARCHAR(100),
    MATRICOLA VARCHAR(100),
    CF VARCHAR(100),
    SESSO VARCHAR(100),
    DT_NASCITA VARCHAR(100),
    TIPO_RAPP VARCHAR(100),
    DT_INI_TIPO_CTR VARCHAR(100),
    DT_FINE_TIPO_CTR VARCHAR(100),
    DT_INI_RAPP VARCHAR(100),
    DT_FINE_RAPP VARCHAR(100),
    AMBITO VARCHAR(100),
    TIPO_ASS VARCHAR(100),
    DT_PROROGA_TERMINE VARCHAR(100),
    DT_CTR_SOST_MAT VARCHAR(100),
    QTA_PART_TIME VARCHAR(100),
    TITOLARE1 VARCHAR(100),
    TITOLARE2 VARCHAR(100),
    MOTIVO_PROMOZIONE VARCHAR(100),
    FASCICOLO_AGGIORNATO VARCHAR(100),
    TITOLO_STUDIO VARCHAR(100),
    DESC_CTR VARCHAR(100),
    DESC_LIV VARCHAR(100)
)
PARTITION BY RANGE (ID_PER)
(
    PARTITION P_202501 VALUES LESS THAN (202502)
);

-- TABELLA DI LOG --
CREATE TABLE STAGE_SPARK.TLOG_LEVEL_ONE (
    ID_RUN      NUMBER(6,0),           -- Numero progressivo di esecuzione del flusso
    ID_PER      NUMBER(6,0),           -- Periodo (es. 202501)
    COD_FLUSSO  VARCHAR2(50 BYTE),     -- Nome del flusso (es. 'PRESENZE', 'ANAGRAFICA', ecc.)
    STEP        NUMBER(3,0),           -- Numero progressivo dello step
    STMT        VARCHAR2(4000 BYTE),   -- Descrizione sintetica dell’operazione
    STATO       VARCHAR2(10 BYTE),     -- 'OK' o 'KO'
    ERROR       VARCHAR2(4000 BYTE),   -- Eventuale messaggio d’errore
    DINS DATE DEFAULT SYSDATE  -- Data/ora inserimento
)
PARTITION BY RANGE (ID_PER)
(
    PARTITION P_202501 VALUES LESS THAN (202502)
);



