CREATE USER DWH_SPARK IDENTIFIED BY DWH_SPARK;

GRANT CONNECT,DBA TO DWH_SPARK;

CREATE TABLE DWH_SPARK.D_ANAGRAFICA_SCD (
    ID_DIP NUMBER(8,0) PRIMARY KEY,
    COD_DIP NUMBER(5,0),
    COD_UNT NUMBER(5,0),
    COD_RUOLO VARCHAR2(10),
    COGNOME VARCHAR2(50),
    NOME VARCHAR2(50),
    DT_INI_UNT DATE,
    TIPO_CTR VARCHAR2(50),
    COD_CTR VARCHAR2(10),
    COD_LIV VARCHAR2(10),
    DT_INI_LIV DATE,
    DT_INI_MNS DATE,
    MATRICOLA VARCHAR2(10),
    CF VARCHAR2(16),
    SESSO VARCHAR2(10),
    DT_NASCITA DATE,
    TIPO_RAPP VARCHAR2(10),
    DT_INI_TIPO_CTR DATE,
    DT_FINE_TIPO_CTR DATE,
    DT_INI_RAPP DATE,
    DT_FINE_RAPP DATE,
    AMBITO VARCHAR2(10),
    TIPO_ASS VARCHAR2(10),
    DT_PROROGA_TERMINE DATE,
    DT_CTR_SOST_MAT DATE,
    QTA_PART_TIME VARCHAR2(10),
    TITOLARE1 VARCHAR2(50),
    TITOLARE2 VARCHAR2(50),
    MOTIVO_PROMOZIONE VARCHAR2(50),
    FASCICOLO_AGGIORNATO VARCHAR2(50),
    TITOLO_STUDIO VARCHAR2(10),
    DESC_CTR VARCHAR2(50),
    DESC_LIV VARCHAR2(50),
    D_INS DATE,
    D_UPD DATE,
    D_INIVAL NUMBER(6,0),
    D_ENDVAL NUMBER(6,0),
    LAST_ID_PER NUMBER(6,0)
);

-- sequenza per ID_DIP
CREATE SEQUENCE DWH_SPARK.SEQ_ANAGRAFICA START WITH 1 INCREMENT BY 1;


CREATE TABLE DWH_SPARK.DIM_UNITA (
    ID_UNT NUMBER(8,0) PRIMARY KEY,
    COD_UNITA VARCHAR2(20) UNIQUE,
    DESC_UNITA VARCHAR2(100),
    D_INS DATE,
    D_UPD DATE,
    LAST_ID_PER NUMBER(8,0)
);

-- Creiamo la sequenza per la surrogate key
CREATE SEQUENCE DWH_SPARK.SEQ_DIM_UNITA START WITH 1 INCREMENT BY 1;



CREATE TABLE DWH_SPARK.DIM_RUOLO (
    ID_RUOLO NUMBER(8,0) PRIMARY KEY,       -- surrogate key
    COD_RUOLO VARCHAR2(20),                 -- codice ruolo originale
    DESCR_RUOLO VARCHAR2(100),              -- descrizione ruolo
    D_INS DATE DEFAULT SYSDATE,             -- data di inserimento
    D_UPD DATE,                              -- data di ultimo aggiornamento
    LAST_ID_PER NUMBER(6,0)                 -- ultimo ID_PERIOD caricato
);

CREATE SEQUENCE DWH_SPARK.SEQ_DIM_RUOLO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


  CREATE TABLE DWH_SPARK.D_PERIOD 
   (	ID_PERIOD NUMBER(8,0), 
	ID_YEAR_MONTH NUMBER(6,0), 
	DAY DATE, 
	DAY_OF_WEEK NUMBER(1,0), 
	DAY_OF_MONTH NUMBER(2,0), 
	DAY_OF_YEAR NUMBER(3,0), 
	DAY_NAME VARCHAR2(20 BYTE), 
	DAY_NAMES VARCHAR2(20 BYTE), 
	FLAG_H NUMBER(1,0), 
	WEEK_OF_MONTH NUMBER(1,0), 
	WEEK_OF_YEAR NUMBER(2,0), 
	MONTH_NUM NUMBER(2,0), 
	MONTH_NUMC VARCHAR2(2 BYTE), 
	MONTH_NAME VARCHAR2(10 BYTE), 
	MONTH_NAMES VARCHAR2(3 BYTE), 
	QUARTER NUMBER(1,0), 
	SEMESTER NUMBER(1,0), 
	YEAR_NUM VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
  CREATE UNIQUE INDEX DWH_SPARK.PERIOD_PK ON DWH_SPARK.D_PERIOD (ID_PERIOD) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
ALTER TABLE DWH_SPARK.D_PERIOD ADD CONSTRAINT PERIOD_PK PRIMARY KEY (ID_PERIOD)
  USING INDEX DWH_SPARK.PERIOD_PK  ENABLE;



CREATE TABLE DWH_SPARK.FCT_PRESENZE (
    ID_PERIOD     NUMBER(8,0),
    ID_YEAR_MONTH NUMBER(6,0),
    ID_DIP        NUMBER(8,0),
    ID_UNT        NUMBER(8,0),
    ID_RUOLO      NUMBER(8,0),
    OREPRES       NUMBER(6,2),
    ORESTRAOR     NUMBER(6,2),
    OREPERMES     NUMBER(6,2),
    CONSTRAINT PK_FCT_PRESENZE PRIMARY KEY (ID_PERIOD, ID_DIP, ID_UNT, ID_RUOLO)
)
PARTITION BY LIST (ID_YEAR_MONTH)
(
    PARTITION P_202501 VALUES (202501),
    PARTITION P_DEFAULT VALUES (DEFAULT)
)
TABLESPACE USERS
PCTFREE 10 PCTUSED 40
INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING;




